# Generated by Django 5.0.3 on 2024-04-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Organisation",
                    fields=[
                        (
                            "info_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        ("info_title", models.CharField(max_length=50, unique=True)),
                    ],
                    options={
                        "abstract": False,
                    },
                ),
            ],
            database_operations=[],
        )
    ]
