# Generated by Django 5.0.3 on 2024-04-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_jobfield"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Contact",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("first_name", models.CharField(max_length=50)),
                        ("last_name", models.CharField(max_length=50)),
                        ("email", models.EmailField(max_length=100)),
                        (
                            "job_field",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="users.jobfield",
                            ),
                        ),
                        (
                            "organisation",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="users.organisation",
                            ),
                        ),
                    ],
                    options={
                        "db_table_comment": "This table contains the contact details of the person who submitted the question",
                    },
                ),
            ],
            database_operations=[],
        )
    ]
