# Generated by Django 5.0.3 on 2024-05-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobfield",
            old_name="info_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="organisation",
            old_name="info_id",
            new_name="id",
        ),
    ]
