version: '3'

services:
  web:
    build: . #Build from current directory 
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: #Map current directory to backend directory 
      - .:/backend
    ports:
    - "8000:8000"
    networks:
      - development
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - 5432
    volumes: 
      - ./opl_backup2.sql:/docker-entrypoint-initdb.d/opl_backup2.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - development
  volumes:
    postgres_data:


  

    
