version: '3'

services:
  web:
    build: . #Build from current directory 
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: #Map current directory to backend directory 
      - .:/backend
    ports:
    - "8000:8000"
    networks:
      - development
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_db
      POSTGRES_DB: OPL_DEV
    ports: 
    - "5433:5432"
    expose:
      - 5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - development
  volumes:
    postgres_data:


  

    
