version: '3'

services:
  web:
    build:
      dockerfile: dockerfile.prod
      context: .
    command: gunicorn OPL.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/backend
      - static_volume:/backend/staticfiles/
    ports:
      - "8001:8000"
    networks:
      - production
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - 5432
    volumes:
      - ./prod-sql-backup2.sql:/docker-entrypoint-initdb.d/prod-sql-backup2.sql
      - postgres_dat_dev:/var/lib/postgresql/data
    networks:
      - production


    
networks:
  production:
    driver: bridge
volumes:
  postgres_data_dev:
  static_volume:
