# Generated by Django 4.2.4 on 2024-02-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0025_alter_openproblems_options_and_more"),
        ("posts_comments", "0019_alter_submissionreferences_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Submission",
            new_name="Post",
        ),
    ]
