# Generated by Django 4.2.4 on 2024-02-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0028_alter_reference_table_comment"),
        ("posts_comments", "0021_rename_submission_id_post_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubmissionReferences",
            new_name="PostReferences",
        ),
    ]
