# Generated by Django 4.2.4 on 2024-02-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0023_alter_postreferences_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postreferences",
            old_name="submission_id",
            new_name="post_id",
        ),
    ]
