# Generated by Django 4.2.4 on 2024-02-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
        ("posts_comments", "0024_rename_submission_id_postreferences_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postreferences",
            name="reference_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="references.reference"
            ),
        ),
    ]
