# Generated by Django 4.2.4 on 2024-02-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "references",
            "0003_alter_author_author_name_alter_journal_journal_name_and_more",
        ),
        ("posts_comments", "0024_rename_submission_id_postreferences_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postreferences",
            name="reference_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="references.reference"
            ),
        ),
    ]
