# Generated by Django 5.0.3 on 2024-03-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_comments', '0024_rename_submission_id_postreferences_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='submission',
            new_name='post',
        ),
    ]
