# Generated by Django 5.0.3 on 2024-03-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0026_rename_comment_id_comment_id"),
        ("references", "0005_reference"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="postreferences",
                    name="reference_id",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.reference",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
