# Generated by Django 5.0.3 on 2024-03-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0027_alter_postreferences_reference_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postreferences",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="postreferences",
            old_name="reference_id",
            new_name="reference",
        ),
    ]
