# Generated by Django 5.0.3 on 2024-03-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0042_remove_relatedproblem_qr_id_and_more"),
        ("posts_comments", "0028_rename_post_id_postreferences_post_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Solution",
        ),
    ]
