# Generated by Django 5.0.3 on 2024-03-15 11:27

from django.db import migrations


def many_to_many_transfer(apps, schema_editor):
    intermediary_model = apps.get_model("posts_comments", "PostReferences")
    for intermediary_model_object in intermediary_model.objects.all():
        post = intermediary_model_object.post
        reference = intermediary_model_object.reference
        post.references.add(reference)


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0030_remove_solution_submitted_references_and_more"),
    ]

    operations = [migrations.RunPython(many_to_many_transfer)]
