# Generated by Django 5.0.3 on 2024-03-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0031_auto_20240315_0627"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submittedreferences",
            name="submission_id",
        ),
        migrations.DeleteModel(
            name="PostReferences",
        ),
        migrations.DeleteModel(
            name="SubmittedReferences",
        ),
    ]
