# Generated by Django 5.0.3 on 2024-03-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0042_remove_relatedproblem_qr_id_and_more"),
        ("posts_comments", "0033_alter_discussion_references_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="open_problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussion",
                to="open_problems.openproblem",
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="open_problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solution",
                to="open_problems.openproblem",
            ),
        ),
    ]
