# Generated by Django 5.0.3 on 2024-03-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "posts_comments",
            "0035_remove_discussion_contact_remove_solution_contact_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="CommentSolution",
        ),
        migrations.CreateModel(
            name="CommentDiscussion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_text", models.TextField()),
                ("alias", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="posts_comments.commentdiscussion",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="posts_comments.solution",
                    ),
                ),
            ],
        ),
    ]
