# Generated by Django 5.0.3 on 2024-04-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_comments", "0036_rename_comment_commentsolution_commentdiscussion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SolutionLike",
        ),
    ]
