# Generated by Django 5.0.3 on 2024-04-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.IntegerField(choices=[])),
                ("detail", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpenProblemReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.IntegerField(choices=[])),
                ("detail", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
