# Generated by Django 5.0.3 on 2024-04-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        ("users", "0004_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalreport",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.contact",
            ),
        ),
    ]
