# Generated by Django 5.0.3 on 2024-04-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_generalreport_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalreport",
            name="contact",
        ),
        migrations.AddField(
            model_name="generalreport",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="generalreport",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="generalreport",
            name="job_field",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="generalreport",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="generalreport",
            name="organisation",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
