# Generated by Django 4.2.4 on 2024-02-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0026_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="duplicate",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="duplicates",
                to="open_problems.openproblems",
            ),
        ),
    ]
