# Generated by Django 4.2.4 on 2024-02-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0026_rename_ref_id_reference_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reference",
            old_name="full_citation",
            new_name="citation",
        ),
    ]
