# Generated by Django 4.2.4 on 2024-02-23 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0028_alter_report_duplicate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="duplicate",
        ),
        migrations.AddField(
            model_name="report",
            name="duplicate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_problem",
                to="open_problems.openproblems",
            ),
        ),
    ]
