# Generated by Django 4.2.4 on 2024-02-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0029_rename_openproblems_openproblem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubmittedProblems",
            new_name="SubmittedProblem",
        ),
    ]
