# Generated by Django 4.2.4 on 2024-02-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0030_rename_submittedproblems_submittedproblem"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="openproblem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="problemreference",
            table=None,
        ),
        migrations.AlterModelTable(
            name="problemrelation",
            table=None,
        ),
        migrations.AlterModelTable(
            name="relatedproblem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="submittedproblem",
            table=None,
        ),
    ]
