# Generated by Django 4.2.4 on 2024-02-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "open_problems",
            "0031_alter_openproblem_table_alter_problemreference_table_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubmittedProblem",
            new_name="SubmittedOpenProblem",
        ),
        migrations.AlterModelTable(
            name="openproblem",
            table="open_problem",
        ),
        migrations.AlterModelTable(
            name="problemreference",
            table="open_problem_reference",
        ),
        migrations.AlterModelTable(
            name="relatedproblem",
            table="related_problem",
        ),
        migrations.AlterModelTable(
            name="submittedopenproblem",
            table="submitted_open_problem",
        ),
    ]
