# Generated by Django 4.2.4 on 2024-02-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0032_rename_submittedproblem_submittedopenproblem_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="author",
            table=None,
        ),
        migrations.AlterModelTable(
            name="journal",
            table=None,
        ),
        migrations.AlterModelTable(
            name="reference",
            table=None,
        ),
        migrations.AlterModelTable(
            name="reftype",
            table=None,
        ),
    ]
