 # Generated by Django 5.0.3 on 2024-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_problems', '0033_alter_author_table_alter_journal_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
        migrations.AddField(
            model_name='openproblem',
            name='references',
            field=models.ManyToManyField(blank=True, to='open_problems.reference'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobfield',
            name='info_title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='info_title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='submittedopenproblem',
            name='references',
        ),
        migrations.AddField(
            model_name='submittedopenproblem',
            name='references',
            field=models.ManyToManyField(blank=True, to='open_problems.reference'),
        ),
    ]
