# Generated by Django 4.2.4 on 2024-02-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
        ("open_problems", "0033_alter_author_table_alter_journal_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openproblem",
            name="references",
            field=models.ManyToManyField(blank=True, to="references.reference"),
        ),
        migrations.AlterField(
            model_name="problemreference",
            name="reference_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="references.reference",
            ),
        ),
    ]
