# Generated by Django 5.0.3 on 2024-03-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_problems', '0034_openproblem_references_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='publish_date',
            new_name='year',
        ),
    ]
