# Generated by Django 4.2.4 on 2024-02-12 09:44

from django.db import migrations


def migrate_problem_references(apps, schema_editor):
    OpenProblem = apps.get_model("open_problems", "OpenProblem")
    ProblemReference = apps.get_model("open_problems", "ProblemReference")
    for pr in ProblemReference.objects.all():
        problem = pr.problem_id
        if problem:
            problem.references.add(pr.reference_id)
            problem.save()


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0034_openproblem_references_and_more"),
    ]

    operations = []
