# Generated by Django 4.2.4 on 2024-02-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0035_auto_20240212_0944"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reference",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="journal_id",
        ),
        migrations.DeleteModel(
            name="RefType",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Journal",
        ),
        migrations.DeleteModel(
            name="Reference",
        ),
    ]
