# Generated by Django 5.0.3 on 2024-03-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_problems', '0035_rename_publish_date_reference_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefType',
        ),
    ]
