# Generated by Django 4.2.4 on 2024-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
        (
            "open_problems",
            "0036_remove_reference_authors_remove_reference_journal_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submittedopenproblem",
            name="references",
        ),
        migrations.AddField(
            model_name="submittedopenproblem",
            name="references",
            field=models.ManyToManyField(blank=True, to="references.reference"),
        ),
    ]
