# Generated by Django 5.0.3 on 2024-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0036_delete_reftype"),
        ("references", "0003_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Author",
                ),
                migrations.AlterField(
                    model_name="reference",
                    name="authors",
                    field=models.ManyToManyField(
                        blank=True, null=True, to="references.author"
                    ),
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Author", table="references_author")
            ],
        )
    ]
