# Generated by Django 5.0.3 on 2024-03-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0037_delete_author_alter_reference_authors"),
        ("references", "0004_journal"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="reference",
                    name="journal_id",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="references.journal",
                    ),
                ),
                migrations.DeleteModel(
                    name="Journal",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Journal", table="references_journal")
            ],
        )
    ]
