# Generated by Django 4.2.4 on 2024-02-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0037_remove_submittedopenproblem_references_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="contact",
            table="contact",
        ),
    ]
