# Generated by Django 4.2.4 on 2024-02-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0038_alter_contact_email_alter_contact_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobfield",
            name="info_title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="info_title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("first_name", "last_name", "email")},
        ),
    ]
