# Generated by Django 5.0.3 on 2024-03-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0022_alter_subjectreference_ref"),
        ("open_problems", "0038_alter_reference_journal_id_delete_journal"),
        ("posts_comments", "0027_alter_postreferences_reference_id"),
        ("references", "0005_reference"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="problemreference",
                    name="reference_id",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="references.reference",
                    ),
                ),
                migrations.AlterField(
                    model_name="openproblem",
                    name="references",
                    field=models.ManyToManyField(blank=True, to="references.reference"),
                ),
                migrations.AlterField(
                    model_name="submittedopenproblem",
                    name="references",
                    field=models.ManyToManyField(blank=True, to="references.reference"),
                ),
                migrations.DeleteModel(
                    name="Reference",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="Reference", table="references_reference"
                )
            ],
        ),
    ]
