# Generated by Django 5.0.3 on 2024-03-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0039_alter_problemreference_reference_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problemreference",
            old_name="problem_id",
            new_name="open_problem",
        ),
        migrations.RenameField(
            model_name="problemreference",
            old_name="reference_id",
            new_name="reference",
        ),
    ]
