# Generated by Django 5.0.3 on 2024-03-15 09:54

from django.db import migrations


# Migration for moving intermediary table to many-to-many field


def transfer_many_to_many(apps, schema_editor):
    intermediary_model = apps.get_model("open_problems", "ProblemReference")
    for intermediary_object in intermediary_model.objects.all():
        open_problem = intermediary_object.open_problem
        reference = intermediary_object.reference
        open_problem.references.add(reference)


class Migration(migrations.Migration):

    dependencies = [
        (
            "open_problems",
            "0040_rename_problem_id_problemreference_open_problem_and_more",
        ),
    ]

    operations = [migrations.RunPython(transfer_many_to_many)]
