# Generated by Django 5.0.3 on 2024-03-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0041_auto_20240315_0454"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relatedproblem",
            name="QR_id",
        ),
        migrations.RemoveField(
            model_name="relatedproblem",
            name="child_id",
        ),
        migrations.RemoveField(
            model_name="relatedproblem",
            name="parent_id",
        ),
        migrations.DeleteModel(
            name="ProblemReference",
        ),
        migrations.DeleteModel(
            name="ProblemRelation",
        ),
        migrations.DeleteModel(
            name="RelatedProblem",
        ),
    ]
