# Generated by Django 5.0.3 on 2024-03-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0042_remove_relatedproblem_qr_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="openproblem",
            table=None,
        ),
    ]
