# Generated by Django 5.0.3 on 2024-04-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0046_alter_contact_organisation_delete_organisation"),
        ("users", "0003_jobfield"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="contact",
                    name="job_field",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.jobfield",
                    ),
                ),
                migrations.DeleteModel(
                    name="JobField",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="JobField", table="users_jobfield")
            ],
        ),
    ]
