# Generated by Django 5.0.3 on 2024-04-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0047_alter_contact_job_field_delete_jobfield"),
        (
            "posts_comments",
            "0037_delete_solutionlike",
        ),
        ("users", "0004_contact"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="openproblem",
                    name="contact",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.contact",
                    ),
                ),
                migrations.AlterField(
                    model_name="submittedopenproblem",
                    name="contact",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.contact",
                    ),
                ),
                migrations.DeleteModel(
                    name="Contact",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Contact", table="users_contact")
            ],
        )
    ]
