# Generated by Django 5.0.3 on 2024-04-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0030_compound_chembl_id"),
        ("open_problems", "0048_alter_openproblem_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openproblem",
            name="compounds",
            field=models.ManyToManyField(blank=True, to="annotations.compound"),
        ),
        migrations.AddField(
            model_name="openproblem",
            name="genes",
            field=models.ManyToManyField(blank=True, to="annotations.gene"),
        ),
        migrations.AddField(
            model_name="openproblem",
            name="species",
            field=models.ManyToManyField(blank=True, to="annotations.species"),
        ),
        migrations.AddField(
            model_name="submittedopenproblem",
            name="compounds",
            field=models.ManyToManyField(blank=True, to="annotations.compound"),
        ),
        migrations.AddField(
            model_name="submittedopenproblem",
            name="genes",
            field=models.ManyToManyField(blank=True, to="annotations.gene"),
        ),
        migrations.AddField(
            model_name="submittedopenproblem",
            name="species",
            field=models.ManyToManyField(blank=True, to="annotations.species"),
        ),
        migrations.AddField(
            model_name="submittedopenproblem",
            name="tags",
            field=models.ManyToManyField(blank=True, to="annotations.tag"),
        ),
    ]
