# Generated by Django 5.0.3 on 2024-04-17 21:47

from django.db import migrations


def migrate_species_problems(apps, schema_editor):
    Species = apps.get_model("annotations", "Species")
    OpenProblem = apps.get_model("open_problems", "OpenProblem")
    SpeciesProblem = apps.get_model("annotations", "SpeciesProblem")

    for species_problem in SpeciesProblem.objects.all():
        open_problem = OpenProblem.objects.get(
            problem_id=species_problem.open_problem.problem_id
        )
        species = Species.objects.get(id=species_problem.species.id)
        open_problem.species.add(species)


def migrate_gene_problems(apps, schema_editor):
    Gene = apps.get_model("annotations", "Gene")
    OpenProblem = apps.get_model("open_problems", "OpenProblem")
    GeneProblem = apps.get_model("annotations", "GeneProblem")

    for gene_problem in GeneProblem.objects.all():
        open_problem = OpenProblem.objects.get(
            problem_id=gene_problem.open_problem.problem_id
        )
        gene = Gene.objects.get(id=gene_problem.gene.id)
        open_problem.genes.add(gene)


class Migration(migrations.Migration):
    dependencies = [
        ("open_problems", "0049_openproblem_compounds_openproblem_genes_and_more"),
        ("users", "0004_contact"),
    ]

    operations = [
        migrations.RunPython(migrate_species_problems),
        migrations.RunPython(migrate_gene_problems),
    ]
