# Generated by Django 5.0.3 on 2024-05-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0050_auto_20240417_1647"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="submittedopenproblem",
            table_comment=None,
        ),
        migrations.AddField(
            model_name="submittedopenproblem",
            name="notify_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name="submittedopenproblem",
            table=None,
        ),
    ]
