# Generated by Django 5.0.3 on 2025-01-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("open_problems", "0051_alter_submittedopenproblem_table_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openproblem",
            name="categories",
            field=models.ManyToManyField(blank=True, to="categories.category"),
        ),
    ]
