# Generated by Django 5.0.3 on 2025-01-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_options"),
        ("open_problems", "0053_alter_openproblem_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openproblem",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="open_problems", to="categories.category"
            ),
        ),
    ]
