# Generated by Django 4.2.4 on 2024-02-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0016_delete_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="species",
            old_name="species_id",
            new_name="id",
        ),
    ]
