# Generated by Django 5.0.3 on 2024-03-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0017_rename_species_id_species_id'),
        ('open_problems', '0034_openproblem_references_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectreference',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subjectreference',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='open_problems.reference'),
        ),
        migrations.AlterField(
            model_name='subjectreference',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='annotations.subject'),
        ),
    ]
