# Generated by Django 4.2.4 on 2024-02-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
        ("annotations", "0017_rename_species_id_species_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectreference",
            name="ref",
            field=models.OneToOneField(
                db_column="reference_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="references.reference",
            ),
        ),
    ]
