# Generated by Django 4.2.4 on 2024-02-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "references",
            "0003_alter_author_author_name_alter_journal_journal_name_and_more",
        ),
        ("annotations", "0017_rename_species_id_species_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subjectreference",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="subjectreference",
            name="ref",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="references.reference",
            ),
        ),
        migrations.AlterField(
            model_name="subjectreference",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="annotations.subject",
            ),
        ),
    ]
