# Generated by Django 5.0.3 on 2024-03-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0018_alter_subjectreference_unique_together_and_more'),
        ('open_problems', '0035_rename_publish_date_reference_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompoundProblems',
            new_name='CompoundProblem',
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterModelTable(
            name='gene',
            table=None,
        ),
        migrations.AlterModelTable(
            name='species',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subject',
            table=None,
        ),
    ]
