# Generated by Django 5.0.3 on 2024-03-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0019_rename_compoundproblems_compoundproblem_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compounds',
            table=None,
        ),
    ]
