# Generated by Django 5.0.3 on 2024-03-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0020_alter_compounds_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compounds',
            new_name='Compound',
        ),
    ]
