# Generated by Django 5.0.3 on 2024-03-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0021_rename_compounds_compound"),
        ("references", "0005_reference"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="subjectreference",
                    name="ref",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="references.reference",
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
