# Generated by Django 5.0.3 on 2024-03-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0022_alter_subjectreference_ref"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subject",
            new_name="Tag",
        ),
        migrations.AlterModelTableComment(
            name="tag",
            table_comment=None,
        ),
        migrations.RenameField(
            model_name="subjectproblem",
            old_name="subject",
            new_name="tag",
        ),
    ]
