# Generated by Django 5.0.3 on 2024-03-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0023_rename_subject_tag_alter_tag_table_comment_and_more"),
        ("open_problems", "0042_remove_relatedproblem_qr_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubjectProblem",
            new_name="TagProblem",
        ),
        migrations.RenameField(
            model_name="subjectreference",
            old_name="ref",
            new_name="reference",
        ),
        migrations.AlterModelTable(
            name="subjectreference",
            table=None,
        ),
    ]
