# Generated by Django 5.0.3 on 2024-03-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0024_rename_subjectproblem_tagproblem_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="tagproblem",
            table_comment=None,
        ),
        migrations.RenameField(
            model_name="compoundproblem",
            old_name="annotation_id",
            new_name="annotation",
        ),
        migrations.RenameField(
            model_name="geneproblem",
            old_name="annotation_id",
            new_name="annotation",
        ),
        migrations.RenameField(
            model_name="speciesproblem",
            old_name="annotation_id",
            new_name="annotation",
        ),
        migrations.RenameField(
            model_name="tagproblem",
            old_name="annotation_id",
            new_name="annotation",
        ),
        migrations.DeleteModel(
            name="SubjectReference",
        ),
    ]
