# Generated by Django 5.0.3 on 2024-03-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0026_alter_tag_title"),
        ("open_problems", "0043_alter_openproblem_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="parent",
        ),
        migrations.AddField(
            model_name="tag",
            name="open_problems",
            field=models.ManyToManyField(blank=True, to="open_problems.openproblem"),
        ),
        migrations.DeleteModel(
            name="TagProblem",
        ),
    ]
