# Generated by Django 5.0.3 on 2024-03-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0027_remove_tag_parent_tag_open_problems_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="open_problems",
        ),
    ]
