# Generated by Django 5.0.3 on 2024-03-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0028_remove_tag_open_problems"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="geneproblem",
            table_comment=None,
        ),
    ]
