# Generated by Django 5.0.3 on 2024-04-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0029_alter_geneproblem_table_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="chembl_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
