# Generated by Django 5.0.3 on 2024-04-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_problems", "0050_auto_20240417_1647"),
        ("annotations", "0030_compound_chembl_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geneproblem",
            name="gene",
        ),
        migrations.RemoveField(
            model_name="geneproblem",
            name="open_problem",
        ),
        migrations.RemoveField(
            model_name="speciesproblem",
            name="open_problem",
        ),
        migrations.RemoveField(
            model_name="speciesproblem",
            name="species",
        ),
        migrations.RenameField(
            model_name="compound",
            old_name="compound_name",
            new_name="name",
        ),
        migrations.DeleteModel(
            name="CompoundProblem",
        ),
        migrations.DeleteModel(
            name="GeneProblem",
        ),
        migrations.DeleteModel(
            name="SpeciesProblem",
        ),
    ]
