# Generated by Django 5.0.3 on 2024-04-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0031_remove_geneproblem_gene_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="pubchem_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
