# Generated by Django 5.0.3 on 2024-04-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0033_alter_compound_chembl_id_alter_compound_pubchem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compound",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
