# Generated by Django 5.0.3 on 2024-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0034_alter_compound_name"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="gene",
            table_comment=None,
        ),
        migrations.AddField(
            model_name="gene",
            name="entrez_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="gene",
            name="gene_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="gene",
            name="gene_symbol",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="gene",
            unique_together={("gene_symbol", "species")},
        ),
    ]
