# Generated by Django 5.0.3 on 2024-04-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0035_alter_gene_table_comment_gene_entrez_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
