# Generated by Django 5.0.3 on 2024-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0036_species_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="species",
            name="genus",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="species",
            name="species",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
