# Generated by Django 5.0.3 on 2024-04-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0040_tag_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gene",
            old_name="gene_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="compound",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gene",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="species",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
