# Generated by Django 5.0.3 on 2024-05-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0041_rename_gene_name_gene_name_compound_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene",
            name="gene_symbol",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
