# Generated by Django 5.0.3 on 2024-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "references",
            "0002_remove_reference_authors_remove_reference_journal_id_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Author",
                    fields=[
                        (
                            "author_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        ("author_name", models.CharField(max_length=50)),
                    ],
                ),
            ],
            database_operations=[],
        )
    ]
