# Generated by Django 4.2.4 on 2024-02-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0002_rename_publish_date_reference_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="author_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="journal_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="citation",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="reference",
            name="doi",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="title",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
