# Generated by Django 5.0.3 on 2024-03-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0003_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Journal",
                    fields=[
                        (
                            "journal_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        ("journal_name", models.CharField(max_length=100)),
                    ],
                    options={
                        "db_table_comment": "Contains the ids and names of article journals",
                    },
                ),
            ],
            database_operations=[],
        )
    ]
