# Generated by Django 5.0.3 on 2024-03-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0004_journal"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Reference",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        ("title", models.CharField(max_length=150)),
                        ("citation", models.TextField()),
                        (
                            "doi",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "relevance",
                            models.PositiveSmallIntegerField(blank=True, null=True),
                        ),
                        ("year", models.CharField(max_length=4)),
                        (
                            "isbn",
                            models.IntegerField(blank=True, max_length=15, null=True),
                        ),
                        (
                            "link",
                            models.CharField(blank=True, max_length=200, null=True),
                        ),
                        (
                            "authors",
                            models.ManyToManyField(
                                blank=True, null=True, to="references.author"
                            ),
                        ),
                        (
                            "journal_id",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="references.journal",
                            ),
                        ),
                    ],
                    options={
                        "db_table_comment": "Contains all reference information",
                    },
                ),
            ],
            database_operations=[],
        )
    ]
