# Generated by Django 5.0.3 on 2024-03-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0006_rename_author_id_author_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
