# Generated by Django 5.0.3 on 2024-03-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0007_alter_journal_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reference",
            name="link",
        ),
        migrations.AlterField(
            model_name="reference",
            name="authors",
            field=models.ManyToManyField(blank=True, to="references.author"),
        ),
    ]
