# Generated by Django 5.0.3 on 2024-03-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0008_remove_reference_link_alter_reference_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="isbn",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
