# Generated by Django 5.0.3 on 2024-03-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0009_alter_reference_isbn"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reference",
            old_name="journal_id",
            new_name="journal",
        ),
    ]
