# Generated by Django 5.0.3 on 2024-03-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0010_rename_journal_id_reference_journal"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="pmid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
