# Generated by Django 5.0.3 on 2024-05-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0011_reference_pmid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reference",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="relevance",
        ),
    ]
